# pandas :
* pandas is a Python library used for working with data sets.

* It has functions for analyzing, cleaning, exploring, and manipulating data.

* The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
# load the data set

data = pd.read_csv('/content/drive/MyDrive/data set/top-1000-most-subscribed-youtube-channels-in-germany (1).csv')

In [4]:
# view top 5 rows
data.head(5)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,Tsuriki Show,"34,100,000","42,490,526,838","4,739",Entertainment,2019
1,2,Kidibli (Kinder Spielzeug Kanal),"29,600,000","15,673,364,837","1,236",Entertainment,2015
2,3,Kurzgesagt – In a Nutshell,"23,600,000","3,145,706,013",271,Education,2013
3,4,boxtoxtv,"23,500,000","18,303,986,629","1,559",Comedy,2022
4,5,HaerteTest,"19,500,000","3,420,864,412","1,712",Science & Technology,2011

In [5]:
data.head(10)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,Tsuriki Show,"34,100,000","42,490,526,838","4,739",Entertainment,2019
1,2,Kidibli (Kinder Spielzeug Kanal),"29,600,000","15,673,364,837","1,236",Entertainment,2015
2,3,Kurzgesagt – In a Nutshell,"23,600,000","3,145,706,013",271,Education,2013
3,4,boxtoxtv,"23,500,000","18,303,986,629","1,559",Comedy,2022
4,5,HaerteTest,"19,500,000","3,420,864,412","1,712",Science & Technology,2011
5,6,Noel Robinson,"18,600,000","10,752,582,783","1,639",Entertainment,2015
6,7,FAMILY BOOMS,"16,800,000","16,225,259,066","1,587",Entertainment,2021
7,8,Talking Angela,"13,300,000","4,116,834,514",345,Entertainment,2014
8,9,Ice Cream Rolls,"12,400,000","1,709,743,695","2,725",Entertainment,2011
9,10,The Voice Kids,"12,200,000","4,238,778,683","1,756",Entertainment,2013

In [6]:
# view bottom rows

data.tail(10)

,rank,Youtuber,subscribers,video views,video count,category,started
990,991,Last Minute Kitchen,"558,000","93,175,555",127,Howto & Style,2014
991,992,Achtung Kontrolle,"558,000","778,332,965","4,262",Entertainment,2018
992,993,WillShorts,"557,000","208,594,430","1,520",Entertainment,2011
993,994,EsKay,"557,000","7,076,051",34,Gaming,2013
994,995,Familie Klickmann,"557,000","362,554,440",154,Entertainment,2023
995,996,Goaltinho,"556,000","177,177,157",654,Sports,2022
996,997,byStegi,"556,000","57,192,052",325,Gaming,2012
997,998,Jasmin Gnu,"556,000","105,664,179",395,People & Blogs,2019
998,999,Beat-Club,"555,000","376,768,424","1,651",https://us.youtubers.me/germany/all/top-1000-m...,2009
999,1000,Mark Kvas,"555,000","67,134,384",35,Gaming,2019

In [7]:
# to find total no of rows and columns
data.shape

(1000, 7)

In [8]:
# to find only rows in the file
data.shape[0]

1000

In [9]:
#to find only columns in the file
data.shape[1]

7

In [10]:
# complete infomation about file
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rank         1000 non-null   int64
 1   Youtuber     1000 non-null   object
 2   subscribers  1000 non-null   object
 3   video views  1000 non-null   object
 4   video count  1000 non-null   object
 5   category     1000 non-null   object
 6   started      1000 non-null   int64
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [11]:
# to find stats discription about numerical columns
data.describe()

              rank      started
count  1000.000000  1000.000000
mean    500.500000  2014.745000
std     288.819436     4.243581
min       1.000000  2005.000000
25%     250.750000  2012.000000
50%     500.500000  2015.000000
75%     750.250000  2018.000000
max    1000.000000  2024.000000

In [12]:
# loction of index file
data.iloc[5:345]

,rank,Youtuber,subscribers,video views,video count,category,started
5,6,Noel Robinson,"18,600,000","10,752,582,783","1,639",Entertainment,2015
6,7,FAMILY BOOMS,"16,800,000","16,225,259,066","1,587",Entertainment,2021
7,8,Talking Angela,"13,300,000","4,116,834,514",345,Entertainment,2014
8,9,Ice Cream Rolls,"12,400,000","1,709,743,695","2,725",Entertainment,2011
9,10,The Voice Kids,"12,200,000","4,238,778,683","1,756",Entertainment,2013
...,...,...,...,...,...,...,...
340,341,Karina2you,"1,390,000","1,271,704,424","1,273",Comedy,2020
341,342,Johnny Hand,"1,390,000","582,818,807","1,871",Entertainment,2016
342,343,flyinguwe,"1,390,000","57,219,623",350,Sports,2007
343,344,Brownies,"1,390,000","327,683,849",938,Entertainment,2014
344,345,ClashGames,"1,380,000","642,709,327","3,585",Gaming,2015

In [13]:
data.loc[7]

rank                        8
Youtuber       Talking Angela
subscribers        13,300,000
video views     4,116,834,514
video count               345
category        Entertainment
started                  2014
Name: 7, dtype: object

In [14]:
data.loc[3:678]

,rank,Youtuber,subscribers,video views,video count,category,started
3,4,boxtoxtv,"23,500,000","18,303,986,629","1,559",Comedy,2022
4,5,HaerteTest,"19,500,000","3,420,864,412","1,712",Science & Technology,2011
5,6,Noel Robinson,"18,600,000","10,752,582,783","1,639",Entertainment,2015
6,7,FAMILY BOOMS,"16,800,000","16,225,259,066","1,587",Entertainment,2021
7,8,Talking Angela,"13,300,000","4,116,834,514",345,Entertainment,2014
...,...,...,...,...,...,...,...
674,675,OST BOYS,"796,000","115,975,946",224,People & Blogs,2016
675,676,Marky,"794,000","167,995,259",419,Gaming,2017
676,677,Köstliche Hausrezepte,"794,000","113,584,909",314,People & Blogs,2023
677,678,2Bough,"793,000","342,827,075","2,486",Entertainment,2006
678,679,Einfaches Rezept,"791,000","149,462,530",662,People & Blogs,2020

In [15]:
# check null values present or not
data.isna()

      rank  Youtuber  subscribers  video views  video count  category  started
0    False     False        False        False        False     False    False
1    False     False        False        False        False     False    False
2    False     False        False        False        False     False    False
3    False     False        False        False        False     False    False
4    False     False        False        False        False     False    False
..     ...       ...          ...          ...          ...       ...      ...
995  False     False        False        False        False     False    False
996  False     False        False        False        False     False    False
997  False     False        False        False        False     False    False
998  False     False        False        False        False     False    False
999  False     False        False        False        False     False    False

[1000 rows x 7 columns]

In [16]:
# in columns
data.isna().any()

rank           False
Youtuber       False
subscribers    False
video views    False
video count    False
category       False
started        False
dtype: bool

In [17]:
data.isnull().sum()

rank           0
Youtuber       0
subscribers    0
video views    0
video count    0
category       0
started        0
dtype: int64

In [18]:
data['Youtuber'].head()

0                        Tsuriki Show
1    Kidibli (Kinder Spielzeug Kanal)
2          Kurzgesagt – In a Nutshell
3                            boxtoxtv
4                          HaerteTest
Name: Youtuber, dtype: object

In [19]:
data[['Youtuber','subscribers']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Youtuber     1000 non-null   object
 1   subscribers  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [20]:
# filter

data[data['started'] >= 2022].head()

,rank,Youtuber,subscribers,video views,video count,category,started
3,4,boxtoxtv,"23,500,000","18,303,986,629","1,559",Comedy,2022
10,11,Electric Squad,"11,700,000","1,108,711,604",244,Gaming,2022
32,33,Nik Wild Animals,"5,490,000","4,475,179,345","1,188",Pets & Animals,2022
37,38,SKITS German,"5,150,000","4,640,958,734","2,964",Howto & Style,2023
41,42,Garri Creative,"4,890,000","1,449,298,471",446,People & Blogs,2022

In [21]:
data[data['category'] == 'Gaming'].head()

,rank,Youtuber,subscribers,video views,video count,category,started
10,11,Electric Squad,"11,700,000","1,108,711,604",244,Gaming,2022
21,22,EugenBro,"6,940,000","2,491,287,963","1,342",Gaming,2015
31,32,Paluten,"5,530,000","5,564,401,210","8,339",Gaming,2012
39,40,Gronkh,"5,000,000","3,886,153,257","16,710",Gaming,2006
44,45,ProsafiaGaming,"4,700,000","4,919,466,523","2,196",Gaming,2010

In [22]:
data[(data['started'] >= 2022) & (data['category'] == 'Gaming')]

,rank,Youtuber,subscribers,video views,video count,category,started
10,11,Electric Squad,"11,700,000","1,108,711,604",244,Gaming,2022
215,216,Cac2us Games,"1,880,000","736,933,117",200,Gaming,2023
221,222,Binzila,"1,850,000","90,071,346",176,Gaming,2022
263,264,ABO3OMAR_FF,"1,650,000","107,492,820",177,Gaming,2023
635,636,CraftedGaming Shorts,"835,000","247,614,709",181,Gaming,2023
714,715,TooBad,"752,000","777,137,430",787,Gaming,2022
727,728,Nedzeer,"738,000","42,374,948",363,Gaming,2023
877,878,MR ViTuBiG,"623,000","21,298,876",517,Gaming,2023

#01-03-2025

In [23]:
import pandas as pd
import seaborn as sns

In [24]:
# rename the column name
data.columns

Index(['rank', 'Youtuber', 'subscribers', 'video views', 'video count',
       'category', 'started'],
      dtype='object')

In [25]:
data = data.rename(columns={'started':'started_year','Youtuber':'youtuber_name'})

In [26]:
data.columns

Index(['rank', 'youtuber_name', 'subscribers', 'video views', 'video count',
       'category', 'started_year'],
      dtype='object')

In [27]:
#identifying outliners using IQR
import numpy as np
data['started_year'].isna().sum()

0

In [28]:
started = data['started_year'].dropna()

In [29]:
q1 =started.quantile(0.25)
q2 =started.quantile(0.50)
q3 =started.quantile(0.75)

iqr = q3 - q3

lower_bound =q1 - 1.5 * iqr
upper_bound =q3 + 1.5 * iqr

In [30]:
outliners = data[(data['started_year'] < lower_bound) | (data['started_year'] > upper_bound)]

print('outliners',outliners[['started_year']])

outliners      started_year
0            2019
3            2022
4            2011
6            2021
8            2011
..            ...
994          2023
995          2022
997          2019
998          2009
999          2019

[440 rows x 1 columns]

In [32]:
# how to create new column in exsting dataset :

data['stage'] = data['started_year'].apply(lambda x: 'senior' if x>=2022 else 'junior')
print(data[['started_year','stage']].head())

   started_year   stage
0          2019  junior
1          2015  junior
2          2013  junior
3          2022  senior
4          2011  junior

In [34]:
print(data[['started_year','stage']].tail(10))

     started_year   stage
990          2014  junior
991          2018  junior
992          2011  junior
993          2013  junior
994          2023  senior
995          2022  senior
996          2012  junior
997          2019  junior
998          2009  junior
999          2019  junior

In [39]:
# group by and aggregation

data_groupby = data.groupby('category').agg({'started_year':['mean','max','min']})
print(data_groupby)

                                                   started_year
                                                           mean   max   min
category
Autos & Vehicles                                    2012.842105  2020  2006
Comedy                                              2015.766667  2023  2006
Education                                           2014.458333  2022  2006
Entertainment                                       2014.158845  2024  2005
Film & Animation                                    2014.720930  2023  2006
Gaming                                              2014.751592  2023  2006
Howto & Style                                       2015.000000  2024  2007
Music                                               2013.118644  2021  2005
News & Politics                                     2011.473684  2019  2005
Nonprofits & Activism                               2012.000000  2016  2010
People & Blogs                                      2016.678788  2024  2005
Pets & Animals                                      2017.100000  2023  2011
Science & Technology                                2012.090909  2018  2006
Shows                                               2016.000000  2016  2016
Sports                                              2014.119048  2023  2006
Travel & Events                                     2012.714286  2021  2006
https://us.youtubers.me/germany/all/top-1000-mo...  2017.545455  2023  2009

In [51]:
# pivoting data
data_pivot = data.pivot_table(index='category',columns='stage',values='started_year',aggfunc='mean')
print(data_pivot)

stage                                                    junior       senior
category
Autos & Vehicles                                    2012.842105          NaN
Comedy                                              2015.037037  2022.333333
Education                                           2014.297872  2022.000000
Entertainment                                       2013.823970  2023.100000
Film & Animation                                    2014.341463  2022.500000
Gaming                                              2014.328859  2022.625000
Howto & Style                                       2013.666667  2023.000000
Music                                               2013.118644          NaN
News & Politics                                     2011.473684          NaN
Nonprofits & Activism                               2012.000000          NaN
People & Blogs                                      2015.993289  2023.062500
Pets & Animals                                      2014.857143  2022.333333
Science & Technology                                2012.090909          NaN
Shows                                               2016.000000          NaN
Sports                                              2013.700000  2022.500000
Travel & Events                                     2012.714286          NaN
https://us.youtubers.me/germany/all/top-1000-mo...  2016.896552  2022.250000

In [59]:
# memory optimization(downcasting)

data['started_year'] = data['started_year'].astype('int16')

data['rank'] = pd.to_numeric(data['rank'], downcast='integer')

print(data.dtypes)

rank              int16
youtuber_name    object
subscribers      object
video views      object
video count      object
category         object
started_year      int16
stage            object
dtype: object

In [60]:
# merge of two data different frames

data1 =sns.load_dataset('titanic')
data2 =sns.load_dataset('tips')

merge_df = pd.merge(data1,data2,on='sex')
print(merge_df.head())

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone, total_bill, tip, smoker, day, time, size]
Index: []

[0 rows x 21 columns]

In [61]:
data1 =sns.load_dataset('titanic')
data1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [62]:
data1.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [65]:
# filling missing values in null values

data1['age'].fillna(data1['age'].mean(),inplace=True)

data1.isna().sum()

<ipython-input-65-ced4e940b116>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1['age'].fillna(data1['age'].mean(),inplace=True)

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [66]:
# where conditional cleaning

data1['fare_category'] = np.where(data1['fare'] > 50,'high','low')
data1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,high
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,high
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,low